package com.prabakaran.libmgmtsys.entities;
// Generated Jan 30, 2022 10:27:58 AM by Hibernate Tools 5.4.7.Final

/**
 * Author generated by hbm2java
 */
public class Author implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer contact;

	public Author() {
	}

	public Author(String name) {
		this.name = name;
	}

	public Author(String name, Integer contact) {
		this.name = name;
		this.contact = contact;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getContact() {
		return this.contact;
	}

	public void setContact(Integer contact) {
		this.contact = contact;
	}

}
