package com.prabakaran.libmgmtsys.entities;
// Generated Jan 30, 2022 10:27:58 AM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Publication generated by hbm2java
 */
public class Publication implements java.io.Serializable {

	private int publicationid;
	private String name;
	private Integer contact;
	private Set books = new HashSet(0);

	public Publication() {
	}

	public Publication(int publicationid, String name) {
		this.publicationid = publicationid;
		this.name = name;
	}

	public Publication(int publicationid, String name, Integer contact, Set books) {
		this.publicationid = publicationid;
		this.name = name;
		this.contact = contact;
		this.books = books;
	}

	public int getPublicationid() {
		return this.publicationid;
	}

	public void setPublicationid(int publicationid) {
		this.publicationid = publicationid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getContact() {
		return this.contact;
	}

	public void setContact(Integer contact) {
		this.contact = contact;
	}

	public Set getBooks() {
		return this.books;
	}

	public void setBooks(Set books) {
		this.books = books;
	}

}
