package com.prabakaran.libmgmtsyssp.entities;
// Generated Jan 30, 2022 10:27:58 AM by Hibernate Tools 5.4.7.Final

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private int bookid;
	private Publication publication;
	private String bookname;

	public Book() {
	}

	public Book(int bookid, String bookname) {
		this.bookid = bookid;
		this.bookname = bookname;
	}

	public Book(int bookid, Publication publication, String bookname) {
		this.bookid = bookid;
		this.publication = publication;
		this.bookname = bookname;
	}

	public int getBookid() {
		return this.bookid;
	}

	public void setBookid(int bookid) {
		this.bookid = bookid;
	}

	public Publication getPublication() {
		return this.publication;
	}

	public void setPublication(Publication publication) {
		this.publication = publication;
	}

	public String getBookname() {
		return this.bookname;
	}

	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

}
